import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Store} from '../server/store.mjs';
import {Agent} from '../server/agent.mjs';
import {Platform} from '../server/platform.mjs';
import {buildPlan,selectDaily} from '../server/planner.mjs';
import {localTime,monday,zonedDateTimeToUtc} from '../server/time.mjs';
import {ProviderError,decodeSolution} from '../server/providers.mjs';
import {judgeResults} from '../server/runner.mjs';
import {createServer} from '../server/http.mjs';
import {catalog} from '../server/catalog.mjs';
function fixture(t,options={}){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'solver-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  const store=new Store(dir),platform=new Platform(store,async()=>({accepted:true,feedback:'Passed'}));
  store.state.config.leetcode.enabled=false;
  const now=options.now||(()=>new Date('2026-09-29T04:30:00Z'));
  const agent=new Agent(store,platform,{now,sleep:async()=>{},complete:async()=>({text:JSON.stringify({code:'def solve(data): return None',explanation:'Example',complexity:'O(1)'}),tokens:40}),...options});
  return {dir,store,platform,agent};
}
test('10 AM IST timing and Monday boundary',()=>{
  assert.equal(localTime(new Date('2026-09-29T04:29:00Z'),'Asia/Kolkata').time,'09:59');
  assert.equal(localTime(new Date('2026-09-29T04:30:00Z'),'Asia/Kolkata').time,'10:00');
  assert.equal(monday('2026-09-29'),'2026-09-28');
  assert.equal(monday('2026-10-04'),'2026-09-28');
  assert.equal(monday('2026-10-05'),'2026-10-05');
  assert.equal(zonedDateTimeToUtc('2026-10-04','11:00','Asia/Kolkata').toISOString(),'2026-10-04T05:30:00.000Z');
});
test('keys encrypted on disk and absent from public state',t=>{
  const {store,dir}=fixture(t);store.setSecret('groq','secret-test-key');
  assert.equal(store.secret('groq'),'secret-test-key');
  assert.ok(!fs.readFileSync(path.join(dir,'state.json'),'utf8').includes('secret-test-key'));
  assert.ok(!JSON.stringify(store.publicState()).includes('secret-test-key'));
  const reloaded=new Store(dir);assert.equal(reloaded.secret('groq'),'secret-test-key');
});
test('updated defaults preserve saved schedule and provider models',t=>{
  const {store,dir}=fixture(t);
  store.state.config.dailyStartTime='17:41';
  store.state.config.models.gemini='custom-model';
  store.state.configSourceHash='previous-release';store.save();
  const reloaded=new Store(dir);
  assert.equal(reloaded.state.config.dailyStartTime,'17:41');
  assert.equal(reloaded.state.config.models.gemini,'custom-model');
});
test('Monday rolling plan starts at basics even if installed midweek',async t=>{
  const {store,platform}=fixture(t);const plan=await buildPlan(store,platform,'2026-09-29');
  assert.equal(plan.days.length,14);assert.equal(plan.start,'2026-09-28');
  assert.equal(plan.days[0].status,'elapsed');assert.equal(plan.days[1].questions[0].id,'two-sum');
  const automatic=store.state.contests.filter(c=>c.autoGenerated);
  assert.equal(automatic.length,2);assert.equal(automatic[0].problemIds.length,4);
  assert.equal(automatic[0].startAt,'2026-10-04T05:30:00.000Z');
  assert.equal(new Set(automatic[0].problemIds).size,4);
  await buildPlan(store,platform,'2026-09-29');
  assert.equal(store.state.contests.filter(c=>c.autoGenerated).length,2);
});
test('automatic weekly contest can be disabled',async t=>{
  const {store,platform}=fixture(t);store.state.config.autoWeeklyContest=false;
  await buildPlan(store,platform,'2026-09-29');assert.equal(store.state.contests.length,0);
});
test('QOTD fallback and unique two-question selection',async t=>{
  const {store,platform}=fixture(t);platform.daily=async()=>{throw Error('offline');};
  const r=await selectDaily(store,platform,'2026-09-29');assert.equal(r.questions.length,2);
  assert.deepEqual(r.questions.map(q=>q.id),['two-sum','contains-duplicate']);assert.match(r.note,/fallback/);
  store.state.config.allowedDifficulties=['Easy'];platform.daily=async()=>catalog.find(p=>p.difficulty==='Hard');
  const easy=await selectDaily(store,platform,'2026-09-29');assert.ok(easy.questions.every(p=>p.difficulty==='Easy'));
});
test('roadmap skips a planned question already accepted as a previous QOTD',async t=>{
  const {store,platform}=fixture(t);store.state.config.preferQuestionOfTheDay=false;
  store.state.jobs.push({id:'daily:2026-09-28',type:'daily',date:'2026-09-28',status:'completed',tasks:[{problem:catalog[0],status:'accepted'}]});
  store.state.plan={days:[{date:'2026-09-29',questions:[catalog[0]]}]};
  const r=await selectDaily(store,platform,'2026-09-29');assert.equal(r.questions[0].id,'contains-duplicate');
});
test('scheduler does not run before ten; runs once per date and persists',async t=>{
  let clock=new Date('2026-09-29T04:29:00Z');
  const {store,agent,dir}=fixture(t,{now:()=>clock});store.setSecret('groq','test');
  await agent.tick();assert.equal(store.state.jobs.length,0);
  clock=new Date('2026-09-29T04:30:00Z');await agent.tick();await Promise.all(agent.running.values());
  assert.equal(store.state.jobs.length,1);assert.equal(store.state.jobs[0].status,'completed');
  await agent.tick();assert.equal(store.state.jobs.length,1);
  assert.equal(new Store(dir).state.jobs[0].status,'completed');
});
test('temporary API failure stops at eight calls and sends notification',async t=>{
  let calls=0;const {store,agent}=fixture(t,{complete:async()=>{calls++;throw new ProviderError('Temporary outage');}});store.setSecret('groq','test');
  const job=agent.createJob('test:retry','contest',[catalog[0]]);await agent.runJob(job);
  assert.equal(calls,8);assert.equal(job.tasks[0].attempts,8);assert.equal(job.status,'failed');
  assert.ok(store.state.notifications.some(n=>n.title==='8-attempt limit reached'));
});
test('wrong answers retry and never count as completed',async t=>{
  const {store,agent,platform}=fixture(t);store.setSecret('groq','test');platform.submit=async()=>({accepted:false,feedback:'Wrong Answer'});
  const job=agent.createJob('test:wrong','contest',[catalog[0]]);await agent.runJob(job);
  assert.equal(job.tasks[0].attempts,8);assert.equal(job.status,'failed');
});
test('quota failure alerts immediately and Gemini backup is used',async t=>{
  const calls=[];const {store,agent}=fixture(t,{complete:async p=>{calls.push(p);if(p==='groq')throw new ProviderError('Quota exhausted','quota');return{text:JSON.stringify({code:'def solve(data): return None'}),tokens:10};}});
  store.setSecret('groq','one');store.setSecret('gemini','two');
  const j=agent.createJob('test:fallback','contest',[catalog[0]]);await agent.runJob(j);
  assert.deepEqual(calls,['groq','gemini']);assert.equal(j.status,'completed');assert.ok(store.state.disabledProviders.groq);
  assert.ok(store.state.notifications.some(n=>n.title==='groq API needs attention'));
});
test('invalid key without backup pauses instead of pretending to pass',async t=>{
  const {store,agent}=fixture(t,{complete:async()=>{throw new ProviderError('Bad key','key');}});store.setSecret('groq','bad');
  const j=agent.createJob('test:key','contest',[catalog[0]]);await agent.runJob(j);
  assert.equal(j.status,'blocked');assert.equal(j.tasks[0].attempts,1);
});
test('budget blocks API calls and is durable',async t=>{
  let calls=0;const {store,agent}=fixture(t,{complete:async()=>{calls++;throw Error();}});store.setSecret('groq','test');store.state.config.dailyTokenBudget=1000;
  const j=agent.createJob('test:budget','contest',[catalog[0]]);await agent.runJob(j);assert.equal(calls,0);assert.equal(j.status,'blocked');
});
test('unavailable Docker judge blocks before spending API tokens',async t=>{
  let calls=0;const {store,platform,agent}=fixture(t,{complete:async()=>{calls++;throw Error();}});store.setSecret('groq','test');
  platform.judge.ready=async()=>{throw Error('Docker not ready');};
  const j=agent.createJob('test:preflight','contest',[catalog[0]]);await agent.runJob(j);
  assert.equal(calls,0);assert.equal(j.status,'blocked');assert.ok(store.state.notifications.some(n=>n.title==='Judge setup required'));
});
test('test contest starts only at its configured start and only once',async t=>{
  let clock=new Date('2026-09-29T03:29:00Z');const {store,agent}=fixture(t,{now:()=>clock});store.setSecret('groq','test');
  store.state.contests.push({id:'owned',name:'Benchmark',startAt:'2026-09-29T03:30:00Z',endAt:'2026-09-29T04:00:00Z',problemIds:['two-sum']});
  await agent.tick();assert.equal(store.state.jobs.length,0);
  clock=new Date('2026-09-29T03:30:00Z');await agent.tick();await Promise.all(agent.running.values());
  assert.equal(store.state.jobs[0].id,'contest:owned');assert.equal(store.state.jobs[0].status,'completed');await agent.tick();assert.equal(store.state.jobs.length,1);
});
test('expired contest does not submit',async t=>{
  const {store,agent}=fixture(t);store.setSecret('groq','test');const j=agent.createJob('test:deadline','contest',[catalog[0]],{endAt:'2026-09-29T04:00:00Z'});
  await agent.runJob(j);assert.equal(j.status,'failed');assert.equal(j.tasks[0].attempts,0);
});
test('API response crossing contest deadline never gets submitted',async t=>{
  let clock=new Date('2026-09-29T03:30:00Z'),submitted=0;
  const {store,platform,agent}=fixture(t,{now:()=>clock,complete:async()=>{clock=new Date('2026-09-29T04:01:00Z');return{text:JSON.stringify({code:'def solve(data): return 1'}),tokens:10};}});store.setSecret('groq','test');
  platform.submit=async()=>{submitted++;return{accepted:true};};
  const j=agent.createJob('test:crossing','contest',[catalog[0]],{endAt:'2026-09-29T04:00:00Z'});await agent.runJob(j);
  assert.equal(submitted,0);assert.equal(j.status,'failed');
});
test('contest reminders persist and do not repeat',async t=>{
  const {store,agent}=fixture(t,{now:()=>new Date('2026-09-29T03:01:00Z')});
  store.state.contests.push({id:'reminder',name:'Upcoming',startAt:'2026-09-29T03:30:00Z',endAt:'2026-09-29T04:00:00Z',problemIds:['two-sum']});
  await agent.tick();await agent.tick();
  assert.equal(store.state.notifications.filter(n=>n.title==='Upcoming test contest').length,1);
});
test('pause prevents scheduled work; manual retry preserves accepted tasks',async t=>{
  const {store,agent}=fixture(t);store.state.config.autoMode=false;await agent.tick();assert.equal(store.state.jobs.length,0);
  const j=agent.createJob('test:manual','daily',catalog.slice(0,2));j.status='failed';j.tasks[0].status='accepted';j.tasks[1].attempts=8;j.tasks[1].status='failed';agent.retry(j.id);
  assert.equal(j.tasks[0].status,'accepted');assert.equal(j.tasks[1].attempts,0);assert.equal(j.status,'queued');
});
test('crashed job restores to queued without erasing attempts',t=>{
  const {store,platform}=fixture(t);store.state.jobs.push({id:'crash',status:'running',tasks:[{status:'solving',attempts:3,problem:catalog[0]}]});new Agent(store,platform);
  assert.equal(store.state.jobs[0].status,'queued');assert.equal(store.state.jobs[0].tasks[0].attempts,3);
});
test('judge compares actual returned values and rejects incomplete output',()=>{
  const cases=[{input:{x:1},expected:2},{input:{x:2},expected:3}];
  assert.equal(judgeResults([2,3],cases).accepted,true);assert.equal(judgeResults([2,4],cases).accepted,false);assert.equal(judgeResults([2],cases).accepted,false);
  assert.throws(()=>decodeSolution('{"explanation":"no code"}'));assert.throws(()=>decodeSolution('garbage'));
});
test('HTTP dashboard requires token, redacts keys and validates config',async t=>{
  const {store,platform,agent}=fixture(t);store.state.config.autoMode=false;store.setSecret('gemini','do-not-expose');
  const server=createServer(store,platform,agent);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));
  const url=`http://127.0.0.1:${server.address().port}`,headers={Authorization:'Bearer '+store.state.adminToken,'Content-Type':'application/json'};
  assert.equal((await fetch(url+'/api/state')).status,401);
  const r=await fetch(url+'/api/state',{headers}),state=await r.json();assert.equal(r.status,200);assert.ok(!JSON.stringify(state).includes('do-not-expose'));
  assert.equal((await fetch(url+'/api/config',{method:'POST',headers,body:JSON.stringify({maxAttempts:9})})).status,400);
  assert.equal((await fetch(url+'/api/contests',{method:'POST',headers,body:JSON.stringify({name:'Owned benchmark',startAt:new Date(Date.now()+60000).toISOString(),endAt:new Date(Date.now()+120000).toISOString(),problemIds:['two-sum']})})).status,201);
  assert.equal((await fetch(url+'/api/leetcode/daily-completion',{method:'POST',headers,body:JSON.stringify({date:'2026-10-05',username:'Leetcoder071',accepted:2,target:2})})).status,200);
  assert.equal(store.state.leetcodeDailyCompletion['2026-10-05'].accepted,2);
  assert.equal((await fetch(url+'/api/leetcode/daily-completion',{method:'POST',headers,body:JSON.stringify({date:'2026-10-05',username:'Leetcoder071',accepted:0,target:2})})).status,400);
  assert.equal((await fetch(url+'/')).status,200);
});

test('live practice uses Gemini backup when Groq is temporarily unavailable',async t=>{
  const calls=[];
  const {store,platform,agent}=fixture(t,{complete:async provider=>{
    calls.push(provider);
    if(provider==='groq')throw new ProviderError('Provider temporarily unavailable','temporary');
    return {text:JSON.stringify({code:'class Solution: pass',explanation:'Draft'}),tokens:30};
  }});
  store.state.config.leetcode.enabled=true;
  store.setSecret('groq','test-groq');store.setSecret('gemini','test-gemini');
  const server=createServer(store,platform,agent);
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const request=()=>fetch(`http://127.0.0.1:${server.address().port}/api/leetcode/solve`,{
    method:'POST',headers:{Authorization:`Bearer ${store.state.adminToken}`,'Content-Type':'application/json'},
    body:JSON.stringify({problem:{title:'Example',statement:'Practice data',starterCode:'class Solution: pass'}})
  });
  store.state.contestCalendar={events:[{title:'Live rated contest',startAt:new Date(Date.now()-60000).toISOString(),endAt:new Date(Date.now()+60000).toISOString()}]};
  const blocked=await request();
  assert.equal(blocked.status,400);assert.match((await blocked.json()).error,/AI solving is paused/);
  assert.deepEqual(calls,[]);
  store.state.contestCalendar.events=[];
  const response=await request();
  assert.equal(response.status,200);assert.equal((await response.json()).provider,'gemini');
  assert.deepEqual(calls,['groq','gemini']);assert.deepEqual(store.state.disabledProviders,{});
  assert.equal(store.publicState().providerHealth.groq.status,'temporary');
  assert.equal(store.publicState().providerHealth.gemini.status,'working');
  assert.deepEqual({provider:store.publicState().providerActivity.provider,fallbackFrom:store.publicState().providerActivity.fallbackFrom},{provider:'gemini',fallbackFrom:'groq'});
});

test('quota-blocked provider becomes available on the next local day',t=>{
  const {store,agent}=fixture(t,{now:()=>new Date('2026-09-30T04:30:00Z')});
  store.setSecret('groq','test');
  store.state.disabledProviders.groq={reason:'API quota or balance unavailable',since:'2026-09-29T13:56:38.398Z'};
  assert.equal(agent.chooseProvider(),'groq');
  assert.equal(store.state.disabledProviders.groq,undefined);
});
