import {addDays,monday,zonedDateTimeToUtc} from './time.mjs';
import {publicProblem} from './catalog.mjs';
export const solvedIds=state=>new Set(state.jobs.flatMap(j=>j.tasks.filter(t=>t.status==='accepted').map(t=>t.problem.id)));
const dayIndex={Monday:0,Tuesday:1,Wednesday:2,Thursday:3,Friday:4,Saturday:5,Sunday:6};
function shuffled(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function ensureAutoContests(store,all,start,currentDate) {
  const c=store.state.config;
  if(c.leetcode?.enabled){store.state.contests=store.state.contests.filter(x=>!x.autoGenerated);return;}
  if(c.platform.type!=='sandbox'||!c.contestMode||!c.autoWeeklyContest)return;
  const last=addDays(start,c.planLengthDays-1),targetDates=[];
  for(let week=0;;week++) {const d=addDays(start,dayIndex[c.autoContestDay]+week*7);if(d>last)break;if(d>=currentDate)targetDates.push(d);}
  const signature=`${c.autoContestDay}|${c.autoContestTime}|${c.autoContestDurationMinutes}|${c.autoContestQuestionCount}|${c.allowedDifficulties.join(',')}`;
  const targetIds=new Set(targetDates.map(d=>`auto-weekly:${d}`));
  store.state.contests=store.state.contests.filter(x=>!x.autoGenerated||!targetIds.has(x.id)||x.scheduleSignature===signature||store.state.jobs.some(j=>j.id==='contest:'+x.id));
  const eligible=all.filter(p=>c.allowedDifficulties.includes(p.difficulty));
  for(const d of targetDates){
    const id=`auto-weekly:${d}`;if(store.state.contests.some(x=>x.id===id))continue;
    const startAt=zonedDateTimeToUtc(d,c.autoContestTime,c.timezone),endAt=new Date(startAt.getTime()+c.autoContestDurationMinutes*60000);
    const problemIds=shuffled(eligible).slice(0,Math.min(c.autoContestQuestionCount,eligible.length)).map(p=>p.id);
    if(problemIds.length)store.state.contests.push({id,name:`Automatic weekly contest · ${d}`,startAt:startAt.toISOString(),endAt:endAt.toISOString(),problemIds,autoGenerated:true,scheduleSignature:signature});
  }
}
export async function buildPlan(store,platform,date) {
  const c=store.state.config, start=monday(date), solved=solvedIds(store.state);
  const all=(await platform.problems()).filter(p=>c.allowedDifficulties.includes(p.difficulty)).sort((a,b)=>(a.order??9999)-(b.order??9999));
  const pending=all.filter(p=>!solved.has(p.id)), review=all.filter(p=>solved.has(p.id));
  const available=[...pending,...review];let cursor=0;
  const days=Array.from({length:c.planLengthDays},(_,n)=>{
    const d=addDays(start,n);
    const completed=store.state.jobs.find(j=>j.id==='daily:'+d);
    const first=c.preferQuestionOfTheDay?1:0;
    const questions=completed?completed.tasks.filter(t=>t.problem.selection!=='QOTD').map(t=>publicProblem(t.problem)):d<date?[]:Array.from({length:c.dailyQuestionCount-first},()=>{const p=available[cursor++%available.length];return p?{...publicProblem(p),review:solved.has(p.id)}:null;}).filter(Boolean);
    return {date:d,time:c.dailyStartTime,qotd:c.preferQuestionOfTheDay,questions,status:completed?.status||(d<date?'elapsed':'planned')};
  });
  ensureAutoContests(store,all,start,date);
  const contests=await platform.contests();
  store.state.plan={generatedAt:new Date().toISOString(),start,days,contests:contests.filter(x=>{const d=new Intl.DateTimeFormat('en-CA',{timeZone:c.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(x.startAt));return d>=start&&d<=addDays(start,c.planLengthDays-1);})};
  store.save();return store.state.plan;
}
export async function selectDaily(store,platform,date) {
  const c=store.state.config, selected=[], all=(await platform.problems()).filter(p=>c.allowedDifficulties.includes(p.difficulty)).sort((a,b)=>(a.order??9999)-(b.order??9999));
  let dailyError='';
  if(c.preferQuestionOfTheDay) {
    try {const p=await platform.daily(date);if(p&&c.allowedDifficulties.includes(p.difficulty))selected.push({...p,selection:'QOTD'});}catch {dailyError='QOTD unavailable; selected roadmap fallback';}
  }
  const solved=solvedIds(store.state), planned=store.state.plan?.days.find(d=>d.date===date)?.questions||[];
  const order=[...planned.map(p=>all.find(x=>x.id===p.id)).filter(p=>p&&!solved.has(p.id)),...all.filter(p=>!solved.has(p.id)),...all];
  for(const p of order) {if(selected.length>=c.dailyQuestionCount)break;if(!selected.some(x=>x.id===p.id))selected.push({...p,selection:solved.has(p.id)?'Revision':'Roadmap'});}
  return {questions:selected,note:dailyError};
}
